//
//  ItemsPresenter.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemsPresentationLogic
{
  func presentFetchItems(response: Items.FetchItems.Response)
}

class ItemsPresenter: ItemsPresentationLogic
{
  weak var viewController: ItemsDisplayLogic?
  
  lazy var currencyFormatter: NumberFormatter = {
    let formatter = NumberFormatter()
    formatter.numberStyle = .currency
    return formatter
  }()
  
  // MARK: Fetch items
  
  func presentFetchItems(response: Items.FetchItems.Response)
  {
    if let items = response.items {
      let displayedItems = Array(items).map { (item) -> Items.FetchItems.ViewModel.DisplayedItem in
        let quantity = String(item.quantity)
        let price = currencyFormatter.string(from: NSNumber(value: item.price))!
        return Items.FetchItems.ViewModel.DisplayedItem(name: item.name, quantity: quantity, price: price)
      }
      let viewModel = Items.FetchItems.ViewModel(displayedItems: displayedItems)
      viewController?.displayFetchItems(viewModel: viewModel)
    }
  }
}
