//
//  ItemsModels.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum Items
{
  // MARK: Use cases
  
  enum FetchItems
  {
    struct Request
    {
    }
    struct Response
    {
      var items: Results<Item>?
    }
    struct ViewModel
    {
      struct DisplayedItem
      {
        var name: String
        var quantity: String
        var price: String
      }
      var displayedItems: [DisplayedItem]
    }
  }
}
