//
//  SellersViewController.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SellersDisplayLogic: class
{
  func displayFetchSellers(viewModel: Sellers.FetchSellers.ViewModel)
}

class SellersViewController: UITableViewController, SellersDisplayLogic
{
  var interactor: SellersBusinessLogic?
  var router: (NSObjectProtocol & SellersRoutingLogic & SellersDataPassing)?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SellersInteractor()
    let presenter = SellersPresenter()
    let router = SellersRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchSellers()
  }
  
  // MARK: Table view
  
  override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
  {
    return displayedSellers.count
  }
  
  override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
  {
    let displayedSeller = displayedSellers[indexPath.row]
    let cell = tableView.dequeueReusableCell(withIdentifier: "SellerCell", for: indexPath)
    cell.textLabel?.text = displayedSeller.name
    cell.detailTextLabel?.text = displayedSeller.email
    return cell
  }
  
  // MARK: Fetch sellers
  
  var displayedSellers = [Sellers.FetchSellers.ViewModel.DisplayedSeller]()
  
  func fetchSellers()
  {
    let request = Sellers.FetchSellers.Request()
    interactor?.fetchSellers(request: request)
  }
  
  func displayFetchSellers(viewModel: Sellers.FetchSellers.ViewModel)
  {
    displayedSellers = viewModel.displayedSellers
    tableView.reloadData()
  }
}
