//
//  SellersPresenter.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SellersPresentationLogic
{
  func presentFetchSellers(response: Sellers.FetchSellers.Response)
}

class SellersPresenter: SellersPresentationLogic
{
  weak var viewController: SellersDisplayLogic?
  
  // MARK: Fetch sellers
  
  func presentFetchSellers(response: Sellers.FetchSellers.Response)
  {
    if let sellers = response.sellers {
      let displayedSellers = Array(sellers).map { Sellers.FetchSellers.ViewModel.DisplayedSeller(name: "\($0.name) - Seller", email: $0.email) }
      let viewModel = Sellers.FetchSellers.ViewModel(displayedSellers: displayedSellers)
      viewController?.displayFetchSellers(viewModel: viewModel)
    }
  }
}
