//
//  TableModels.swift
//  Auction
//
//  Created by Raymond Law on 1/20/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol DisplayedObject
{
  
}

enum Table
{
  enum Displayable: Int
  {
    case items = 0
    case buyers = 1
    case sellers = 2
  }
  
  // MARK: Use cases
  
  enum FetchObjects
  {
    struct Request
    {
      var displayable: Displayable
    }
    struct Response
    {
      var objects: Results<Object>?
    }
    struct ViewModel
    {
      struct DisplayedItem: DisplayedObject
      {
        var name: String
        var quantity: String
        var price: String
      }
      struct DisplayedBuyer: DisplayedObject
      {
        var name: String
        var email: String
      }
      struct DisplayedSeller: DisplayedObject
      {
        var name: String
        var email: String
      }
      var displayedObjects: [DisplayedObject]
    }
  }
}
