//
//  BuyersModels.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum Buyers
{
  // MARK: Use cases
  
  enum FetchBuyers
  {
    struct Request
    {
    }
    struct Response
    {
      var buyers: Results<User>?
    }
    struct ViewModel
    {
      struct DisplayedBuyer
      {
        var name: String
        var email: String
      }
      var displayedBuyers: [DisplayedBuyer]
    }
  }
}
