//
//  BuyersViewController.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyersDisplayLogic: class
{
  func displayFetchBuyers(viewModel: Buyers.FetchBuyers.ViewModel)
}

class BuyersViewController: UITableViewController, BuyersDisplayLogic
{
  var interactor: BuyersBusinessLogic?
  var router: (NSObjectProtocol & BuyersRoutingLogic & BuyersDataPassing)?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = BuyersInteractor()
    let presenter = BuyersPresenter()
    let router = BuyersRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchBuyers()
  }
  
  // MARK: Table view
  
  override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
  {
    return displayedBuyers.count
  }
  
  override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
  {
    let displayedBuyer = displayedBuyers[indexPath.row]
    let cell = tableView.dequeueReusableCell(withIdentifier: "BuyerCell", for: indexPath)
    cell.textLabel?.text = displayedBuyer.name
    cell.detailTextLabel?.text = displayedBuyer.email
    return cell
  }
  
  // MARK: Fetch buyers
  
  var displayedBuyers = [Buyers.FetchBuyers.ViewModel.DisplayedBuyer]()
  
  func fetchBuyers()
  {
    let request = Buyers.FetchBuyers.Request()
    interactor?.fetchBuyers(request: request)
  }
  
  func displayFetchBuyers(viewModel: Buyers.FetchBuyers.ViewModel)
  {
    displayedBuyers = viewModel.displayedBuyers
    tableView.reloadData()
  }
}
