//
//  BuyersPresenter.swift
//  Auction
//
//  Created by Raymond Law on 1/17/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyersPresentationLogic
{
  func presentFetchBuyers(response: Buyers.FetchBuyers.Response)
}

class BuyersPresenter: BuyersPresentationLogic
{
  weak var viewController: BuyersDisplayLogic?
  
  // MARK: Fetch buyers
  
  func presentFetchBuyers(response: Buyers.FetchBuyers.Response)
  {
    if let buyers = response.buyers {
      let displayedBuyers = Array(buyers).map { Buyers.FetchBuyers.ViewModel.DisplayedBuyer(name: "\($0.name) - Buyer", email: $0.email) }
      let viewModel = Buyers.FetchBuyers.ViewModel(displayedBuyers: displayedBuyers)
      viewController?.displayFetchBuyers(viewModel: viewModel)
    }
  }
}
